### PR TITLE
perf: use replaceAll instead of replacing plus

### PR DESCRIPTION
**Pull request by anonrig**
Solves https://github.com/anonrig/fast-querystring/issues/1

### CODE REVIEW

**Comment by Fdawgs** [comment]
Is `replaceAll` actually faster in this instance?
From other benchmarks, it's slower, see [RafaelGSS/nodejs-bench-operations](https://github.com/RafaelGSS/nodejs-bench-operations/blob/main/RESULTS-v18.md#replace-vs-replaceall-comparison)

**Comment by anonrig** [comment]
The benchmarks are quite flaky but here's my benchmark on node 18.8.0

```javascript
import benchmark from "cronometro";

const input = "1+2+3+4+5+6+7+8+9";

await benchmark(
  {
    replaceAll() {
      return input.replaceAll("+", " ");
    },
    replace() {
      return input.replace(/\+/g, " ");
    },
  },
  { warmup: true },
);
```

with a result:

```
╔══════════════╤═════════╤═══════════════════╤═══════════╗
║ Slower tests │ Samples │            Result │ Tolerance ║
╟──────────────┼─────────┼───────────────────┼───────────╢
║ replace      │   10000 │ 2783621.84 op/sec │  ± 9.02 % ║
╟──────────────┼─────────┼───────────────────┼───────────╢
║ Fastest test │ Samples │            Result │ Tolerance ║
╟──────────────┼─────────┼───────────────────┼───────────╢
║ replaceAll   │    7500 │ 3117273.06 op/sec │  ± 0.97 % ║
╚══════════════╧═════════╧═══════════════════╧═══════════╝
```

**Comment by Fdawgs** [comment]
Thanks @anonrig!

**Comment by anonrig** [comment]
Thank you for asking!

**Pull request merged**
