### PR TITLE
perf: 15 % better perf for number to string, avoid intermediate Math.abs, use implicit number to string coercion

### PR DESCRIPTION
**Pull request by Uzlopak**
The reason why we do Math.abs is because 1e21.toString() returns "1e+21". + gets encoded but - not. So there is no good reason to do a Math.abs call. We only need to know if the number is bigger or equal than 1e21.

We could probably optimize also the >= 1e21 case because we only need to replace the +. But I guess that case is actually neglectable, because we are already bigger than Number.MAX_SAFE_INTEGER.

My benchmarks showed that doing 

```js
const tmp = value.toString(); 
const pos = tmp.indexOf('+'); 
return value.slice(0, pos) + '%2B' + value.slice(pos + 1);
```

could be faster than calling encodeString.

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

**Comment by anonrig** [comment]
Thanks! Nice catch. Can you provide the benchmark result for this @Uzlopak?

**Comment by Uzlopak** [comment]
See #25 
First add the fine grained benchmarks. Maybe also add more more cases. The we can bench more.

E.g. i think 
```js
"" + value 
```

Is faster than
```js
 value.toString()
```

**Comment by anonrig** [comment]
@Uzlopak Can you update the branch and run a benchmark?

**Comment by Uzlopak** [comment]
So it brings about 15 % more perf for number stringification

**Comment by Uzlopak** [comment]
I dont get why the test coverage is supposedly lower. Probably because it is now one line less?! Anyway, i created #30 to counter the coverage issue

**Pull request merged**
