### PR TITLE
add dependabot.yml, switch to npm

### PR DESCRIPTION
**Pull request by Uzlopak**
As discussed in #27 

Merge errors and rebasing etc. in github sucks sometimes. 

@anonrig 
@Fdawgs

### CODE REVIEW

**Review by anonrig — APPROVED** [review]
You are the best.

**Comment by anonrig** [comment]
@Uzlopak Can you update rome too?

**Comment by Uzlopak** [comment]
yes, done

**Comment by Fdawgs** [comment]
LGTM!

**Pull request merged**
